platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  # If you want to use the base implementation:
  pod 'GoogleMLKit/PoseDetection', '2.5.0'

  # If you want to use the accurate implementation:
  pod 'GoogleMLKit/PoseDetectionAccurate', '2.5.0'
  pod 'MLKitXenoCommon'
end

target 'PluginTests' do
  capacitor_pods
end
